(defmacro deftest (name expected form)
  `(let ((got ,form))
     (if (equal got ,expected) (print (list 'pass ',name))
         (print (list 'FAIL ',name 'got got)))))
(deftest ds-flat 6 (destructuring-bind (a b c) '(1 2 3) (+ a b c)))
(deftest ds-nested 6 (destructuring-bind (a (b c)) '(1 (2 3)) (+ a b c)))
(deftest ds-deep 10 (destructuring-bind (a (b (c d))) '(1 (2 (3 4))) (+ a b c d)))
(deftest ds-rest '(2 3) (destructuring-bind (a &rest r) '(1 2 3) r))
(deftest ds-optional 9 (destructuring-bind (a &optional (b 9)) '(0) b))
