;;;; PyTorch Lightning driven from Common Lisp, with the boilerplate
;;;; generated by a macro.
;;;;
;;;; A LightningModule is four methods of which three are always the same
;;;; shape.  That is exactly the kind of repetition a macro is for.

(py-import torch)
(py-import torch.utils.data)
(py-import lightning)

;;; --- the macro -------------------------------------------------------
;;;
;;; (deflit my-net ((torch.nn.Linear 1 8) (torch.nn.ReLU) (torch.nn.Linear 8 1))
;;;         :lr 0.05)
;;; expands into the whole class definition.

(defmacro deflit (name layers &key (lr 0.1))
  `(setq ,name
     (py-class ,(string name)
               (list lightning.LightningModule)
               "__init__"
               (lambda (self)
                 (py-call (py-attr lightning.LightningModule "__init__") self)
                 (py-set-attr self "net" (torch.nn.Sequential ,@layers)))
               "forward"
               (lambda (self x)
                 (py-call (py-attr self "net") x))
               "training_step"
               (lambda (self batch idx)
                 (py-call torch.nn.functional.mse_loss
                          (py-call (py-attr self "net") (py-getitem batch 0))
                          (py-getitem batch 1)))
               "configure_optimizers"
               (lambda (self)
                 (py-call torch.optim.SGD
                          (py-method self "parameters")
                          :lr ,lr)))))

;;; --- use it ----------------------------------------------------------

(deflit linear-net ((torch.nn.Linear 1 1)) :lr 0.1)

(defun make-loader (n batch)
  (let* ((xs (torch.randn n 1))
         (ys (py-call torch.mul xs 3.0)))
    (py-call torch.utils.data.DataLoader
             (torch.utils.data.TensorDataset xs ys)
             :batch_size batch)))

(defun quiet-trainer (epochs)
  (py-call lightning.Trainer
           :max_epochs epochs
           :accelerator "cpu"
           :logger py-false
           :enable_progress_bar py-false
           :enable_checkpointing py-false
           :enable_model_summary py-false))

(setq model (py-call linear-net))
(setq loader (make-loader 128 16))

(print (list 'weight-before
             (py-method (py-method (py-attr model "net") "parameters") "__next__")))

(py-method (quiet-trainer 30) "fit" model loader)

;;; the model should have learned y = 3x
(setq w (py-method (py-getitem (py-list (py-method model "parameters")) 0) "item"))
(print (list 'learned-weight w))
(print (list 'close-to-3 (if (< (py-call abs (- w 3.0)) 0.5) 'yes 'no)))
